### PR TITLE
Removed Animation and added drawer content

### LINKED ISSUE #10: Adding Content to Drawer
The drawer is displayed after double tap on the menu icon. The empty space can be replaced by the actual menu content.

### PR DESCRIPTION
**Pull request by HimeshNayak**
- Fixes #10 
- Removed the animation code
- Removed menuIcon from drawer
- Added content to drawer

Please have a look and let me know is anything else is needed.

### CODE REVIEW

**Review by Harshit564 — CHANGES_REQUESTED** [review]
Don't remove the animation. Just add some content or image (showing the navigation for double tap) to the blank screen when tapped once on the drawer.

**Comment by HimeshNayak** [comment]
Okay I'll add a text stating the user to tap on the menu icon.

**Review by sarveshsrv — CHANGES_REQUESTED** [review]
@HimeshNayak  Removing the animation is not a good choice here. Better you may try to add an alertDialog quoting "double-tap" , if it suits.  Rest is cool @Harshit564 .

**Comment by HimeshNayak** [comment]
I have added the animation on init of the drawer and added a text which can be replaced by any other text or image as provided. Please have a look.

**Pull request merged**
